project:
  type: website

website:
  title: "Diego Lopes da Silva"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css   # <- make sure this file is in the project root
